language: go

go:
  - '1.11.2'

env:
  - GO111MODULE=on

install: true

script:
  - make build
  - make dist

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ebwTtWZWQKfUop1hjdOMD9y4kIgtWRd79xhe/NVCF3tEsYyVX0zU6iRigLgQcCU8fl6/pAqDGZ78bQUS8mCm7gVuDKZsIcYfVjdPt5bmE70px/U4wSYairDJa/gQRWtIAgyYycG6l7ghAFnL8CX6vSUdkULWHM/7eUkqcGGfQgDHo2Jo2+1uMA50/1K6XSODYI7g0aRpO+rGlHUJPiGx+Q1En+BwF2nHHrVgxN5+k40BGd3dkj3zUekmtgCZKAliJjx3aWuqDn5KutwYmYcpAexLYeFDeBpHwWtOToFTRcEB1h9tTHym0ZwZ6q5Xu3hTSjWdVvssv5zaTES5lG9WBo/M4IW1ZLO3K1bxWCe+R4gBsC92yBuDkBtqF7MX4QX/Mc+NgAUK0SUaVsIt6BPyAk7cT5ekG5yg7pS+BfIP5mX6ZioSVssgGFvbeEuyj0yKogAMlbFMvk6c2SZc0LJf4wTQvIRCrvFVWrSM+NXhoEzN2xpGulVnZhr405OvLcQdad/XEwOGyBPTFp9kR3Pz3nJwEEl1iEasVvOHX+orA1Qv4QN0Mxjm9+L92iayWxZCcW1b0o2f6ukfTlZwB39WEA4V4z2SeAaLuwAINhwMxnGpcxPiL/OwRP4kOxbEmnNi7QPWjqsLmO3yWhNNeSmChI5XHbzpy1eut12YRkesnp4=
  file_glob: true
  file: dist/*
  on:
    tags: true
    repo: karriereat/commit-message-bot
