[Server]
LogLevel = "debug"
Port = 8888

[Gitlab]
Token = "SECRET-TOKEN"

[CommitLog]
Type = "logstash"
Server = "LOGSTASH-SERVER"
Servicename = "commit-message"

[Slack]
Token = "SLACK-OAUTH-TOKEN"
Emoji = ":cop:"
FallbackUser = "SLACK-FALLBACK-USER"

[Filters]
Startings = ["Merge branch", "Merge remote-tracking", "Revert ", "Automated Jenkins commit"]
Emails = ["john.doe@example.com"]
Groups = ["internal"]

[Database]
Path = "./ref.db"